name: CI/CD Pipeline - Projeto Coleta

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Setup do JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build com Maven
        run: mvn clean package -DskipTests

      - name: Build da imagem Docker
        run: |
          docker build -t projeto-coleta .

      # Aqui você pode adicionar deploy para staging e produção depois
