name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - staging
  workflow_dispatch:  # permite executar manualmente

jobs:
  build-and-push:
    name: Build & Push Docker image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/springboot-app:${{ github.ref_name }}

  deploy-staging:
    name: Deploy to Staging
    needs: build-and-push
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/staging'

    steps:
      - name: Simulate deploy to staging
        run: echo 'Deploying to staging using image:${{ secrets.DOCKER_USERNAME }}/springboot-app:staging'

  deploy-production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: build-and-push
    if: github.event_name == 'workflow_dispatch'

    steps:
      - name: Simulate deploy to production
        run: echo 'Deploying to production using image:${{ secrets.DOCKER_USERNAME }}/springboot-app:main'
